model: "HistGradientBoostingRegressor"

params:
  l2_regularization: 0.230893825622149
  learning_rate: 0.0823076398078035
  max_bins: 187
  max_depth: 9
  max_iter: 527
  min_samples_leaf: 17
  random_state: 42